#! /bin/bash

PREFIX="`echo $1 | awk -F . '{print $1}'`"
SUBDOMAIN="`echo $1 | awk -F . '{print $2}'`"

echo "$PREFIX $SUBDOMAIN"

GREP=$(grep "$PREFIX[[:space:]]*IN[[:space:]]*A" /etc/bind/zones/mrt-zones/db.$SUBDOMAIN.bram-verbist.sb.uclllabs.be)

if [ -z "$GREP" ];
then
echo "prefix or subdomain not found"
else
        mkdir /var/www/html/$PREFIX.$SUBDOMAIN
        touch /var/www/html/$PREFIX.$SUBDOMAIN/index.html
        echo "welcome $PREFIX.$SUBDOMAIN" > /var/www/html/$PREFIX.$SUBDOMAIN/index.html

        touch /etc/apache2/sites-available/$PREFIX.$SUBDOMAIN.bram-verbist.sb.uclllabs.be.conf
        echo
        "<VirtualHost *:80>
                ServerName $1
                DocumentRoot /var/www/html/$PREFIX.$SUBDOMAIN
        </VirtualHost>" > /etc/apache2/sites-available/$PREFIX.$SUBDOMAIN.conf

        a2ensite $PREFIX.$SUBDOMAIN.bram-verbist.sb.uclllabs.be.conf
        systemctl reload apache2
fi
