#! /bin/bash

SUBDOMAIN="`echo $1 | awk -F . '{print $1}'`"

echo "$SUBDOMAIN"

GREP=$(grep "$SUBDOMAIN[[:space:]]*IN[[:space:]]*A" /etc/bind/zones/db.bram-verbist.sb.uclllabs.be)

if [ -z "$GREP" ];
then
echo "subdomain not found"
else
	mkdir /var/www/html/$SUBDOMAIN
	touch /var/www/html/$SUBDOMAIN/index.html
	echo "welcome $SUBDOMAIN" > /var/www/html/$SUBDOMAIN/index.html

	echo "@ IN A 193.191.177.142" >> /etc/bind/zones/mrt-zones/db.$SUBDOMAIN.bram-verbist.sb.uclllabs.be
	perl -i -pe '/Serial/ && s/(\d+)/$1+1 . $2/e' /etc/bind/zones/mrt-zones/db.$SUBDOMAIN.bram-verbist.sb.uclllabs.be
	rndc reload

	touch /etc/apache2/sites-available/$SUBDOMAIN.bram-verbist.sb.uclllabs.be.conf
	printf "<VirtualHost *:80>
	ServerName $1
	DocumentRoot /var/www/html/$SUBDOMAIN
</VirtualHost>" > /etc/apache2/sites-available/$SUBDOMAIN.bram-verbist.sb.uclllabs.be.conf

	a2ensite $SUBDOMAIN.bram-verbist.sb.uclllabs.be.conf
	systemctl reload apache2
fi
